parameters:
    fsc_hateoas.factory.link.class: FSC\HateoasBundle\Factory\LinkFactory
    fsc_hateoas.serializer.event_subscriber.link.class: FSC\HateoasBundle\Serializer\EventSubscriber\LinkEventSubscriber
    fsc_hateoas.serializer.event_subscriber.embedder.class: FSC\HateoasBundle\Serializer\EventSubscriber\EmbedderEventSubscriber

services:
    fsc_hateoas.factory.link:
        class: %fsc_hateoas.factory.link.class%
        arguments:
            - @router
            - @fsc_hateoas.metadata.factory

    fsc_hateoas.serializer.event_subscriber.link:
        class: %fsc_hateoas.serializer.event_subscriber.link.class%
        arguments:
            - @fsc_hateoas.factory.link
        tags:
            - { name: jms_serializer.event_subscriber }

    fsc_hateoas.serializer.event_subscriber.embedder:
        class: %fsc_hateoas.serializer.event_subscriber.embedder.class%
        arguments:
            - @fsc_hateoas.metadata.factory
            - @jms_serializer.metadata_factory
            - @service_container
        tags:
            - { name: jms_serializer.event_subscriber }
